"""empty message

Revision ID: 94019ff2f557
Revises: 402b109ddb70
Create Date: 2023-01-30 08:19:25.300804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94019ff2f557'
down_revision = '402b109ddb70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=False))
        batch_op.drop_column('amount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.FLOAT(), nullable=False))
        batch_op.drop_column('description')

    # ### end Alembic commands ###
